title: Security Key
description: What is a security key and how it keeps your account safe, simple security now is possible
repository: lenorix/security-key-info-web
url: https://securitykey.info

remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-remote-theme
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
  - jekyll-feed
  - jekyll-tailwindcss

sass:
  style: compressed

jekyll-minifier:
  preserve_php: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: false               # Default: true
  compress_javascript: true         # Default: true
  compress_json: true               # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: true       # Default: false
  preserve_patterns:                # Default: (empty)
  uglifier_args:                    # Default: (empty)
    harmony: true

titles_from_headings:
  strip_title: true
